asdsfsd
greenway-start/gws-frontend pull request #1
Opened 2024-05-16 11:12 UTC by 5heral

2024-05-16 11:25 UTC, khanZhomart commented
Обычно принято описывать действие в названии pull request.

Пример (на слово LOG-86 внимания не обращай):
![image](https://github.com/greenway-start/gws-frontend/assets/71120576/e4fe3ddb-5e3b-4c14-8481-33e5951c28a6)

2024-05-16 11:32 UTC, khanZhomart requested changes

2024-05-16 11:32 UTC, khanZhomart commented on src/App.jsx
> +class App extends React.Component {
В современном React сейчас используют `functional components`. Классовые компоненты `class App` уже устарели и редко используются

https://www.geeksforgeeks.org/differences-between-functional-components-and-class-components/

2024-05-16 11:32 UTC, khanZhomart commented on src/App.jsx
> +        this.state = {
В функциональных компонентах существуют `hooks` и для управления состоянием юзают `useState`. Много документации по нему, можешь почитать

2024-05-16 11:32 UTC, khanZhomart commented on src/components/AddBook.js
> +class AddBook extends React.Component {
Тоже самое что и с `class App`

2024-05-16 11:32 UTC, khanZhomart commented on src/components/AddBook.js
> +                <button
Попробуй вместо обычных html-тегов использовать `React-Bootstrap` компоненты, так будет лучше :)

2024-05-16 11:32 UTC, khanZhomart commented on src/components/AddBook.js
> +                    onChange={(e) => this.setState({ avtor: e.target.value })}
Давай попробуем сделать валидацию для этих полей при вводе:

1. В имени автора не должно быть цифр
2. Название книги не должно быть больше 100 символов

Если валидация не проходит, то показывается ошибка над формой заполнения

2024-05-17 06:17 UTC, 5heral commented on src/components/AddBook.js
> +                <button
тут же я как понял, html компоненты просто заменяются трап с некоторыми изменениями да?

2024-05-17 07:11 UTC, khanZhomart commented on src/components/AddBook.js
> +                <button
Да, компоненты дают больше возможностей настройки, обработки значений вводимых и так далее. с html-тегами всё это надо самому с нуля делать.

Считай эти компоненты это просто обёртки вокруг html-тегов. Внутри они тоже их используют, просто оборачивают и предоставляют инструменты и прикольные фишки

2024-05-17 07:15 UTC, khanZhomart requested changes

2024-05-17 07:15 UTC, khanZhomart commented on src/components/Book.js
> +class Book extends React.Component {
Здесь в функциональный компонент надо поменять и файлы с компонентами должны быть `.jsx`

2024-05-17 07:15 UTC, khanZhomart commented on src/components/Books.js
> +class Books extends React.Component {
Тоже самое, что и с Book

2024-05-17 07:15 UTC, khanZhomart commented on src/components/Header.js
> +class Header extends React.Component {
Функциональный компонент и `.jsx`

2024-05-17 10:28 UTC, khanZhomart requested changes

2024-05-17 10:28 UTC, khanZhomart commented on src/components/Books.jsx
> +const Books = ({ books, onEdit, onDelete }) => {
Здесь можно визуально удобнее и более читаемым сделать компонент:

```
const Books = (...) => {

   if (books.length < 1) {
       return (
                <div className="book">
                    <h3>Книг нет</h3>
                </div>
       )
   }

   return (
        ...
   )
}
```

По сути тоже самое, но так проще читается для других

2024-05-17 10:45 UTC, khanZhomart approved these changes
Норм, поздравляю с первым Approve 👍

2024-05-17 10:45 UTC, merged